BOT_NAME = 'broad'

SPIDER_MODULES = ['broad.spiders']
NEWSPIDER_MODULE = 'broad.spiders'

CONCURRENT_REQUESTS = 100
SEEDS = 'company200k.txt'
COOKIES_ENABLED = False
RETRY_ENABLED = False
DOWNLOAD_TIMEOUT = 15
AJAXCRAWL_ENABLED = True
DOWNLOAD_MAXSIZE = 512*1024
DOWNLOAD_WARNSIZE = 128*1024

DEPTH_PRIORITY = 1
SCHEDULER_DISK_QUEUE = 'scrapy.squeues.PickleFifoDiskQueue'
SCHEDULER_MEMORY_QUEUE = 'scrapy.squeues.FifoMemoryQueue'
